// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetECSDetail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.OperationResult>;

export function GetECSMetrics(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CMSMetricsResult>;

export function GetECSMetricsMultiRegion(arg1:string,arg2:string,arg3:Array<Record<string, string>>):Promise<main.CMSMetricsResult>;

export function MaskKey(arg1:string):Promise<string>;

export function QueryECS(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.QueryECSResult>;

export function QueryECSMultiRegion(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<main.MultiRegionResult>;

export function RebootECS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<main.OperationResult>;

export function StartECS(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.OperationResult>;

export function StopECS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<main.OperationResult>;
