// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MaskKey(arg1) {
  return window['go']['main']['App']['MaskKey'](arg1);
}

export function QueryECS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryECS'](arg1, arg2, arg3, arg4);
}
