// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetECSDetail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetECSDetail'](arg1, arg2, arg3, arg4);
}

export function MaskKey(arg1) {
  return window['go']['main']['App']['MaskKey'](arg1);
}

export function QueryECS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryECS'](arg1, arg2, arg3, arg4);
}

export function QueryECSMultiRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryECSMultiRegion'](arg1, arg2, arg3, arg4);
}

export function RebootECS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RebootECS'](arg1, arg2, arg3, arg4, arg5);
}

export function StartECS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartECS'](arg1, arg2, arg3, arg4);
}

export function StopECS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StopECS'](arg1, arg2, arg3, arg4, arg5);
}
