// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetECSDetail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.OperationResult>;

export function GetECSMetrics(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CMSMetricsResult>;

export function GetECSMetricsMultiRegion(arg1:string,arg2:string,arg3:Array<Record<string, string>>):Promise<main.CMSMetricsResult>;

export function ListOSSBuckets(arg1:string,arg2:string,arg3:string):Promise<main.OSSBucketResult>;

export function ListOSSObjects(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.OSSObjectResult>;

export function ListSLSLogStores(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SLSLogStoreResult>;

export function MaskKey(arg1:string):Promise<string>;

export function QueryECS(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.QueryECSResult>;

export function QueryECSMultiRegion(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<main.MultiRegionResult>;

export function QuerySLSLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:number):Promise<main.SLSLogQueryResult>;

export function QuerySLSLogsStream(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:number):Promise<main.SLSStreamResult>;

export function RebootECS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<main.OperationResult>;

export function StartECS(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.OperationResult>;

export function StopECS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<main.OperationResult>;

export function GetSupportedCloudProducts():Promise<main.CloudProductResult>;

export function GetCloudProductMetrics(arg1:string):Promise<main.CloudProductResult>;

export function ListVPCs(arg1:string,arg2:string,arg3:string):Promise<main.VPCListResult>;

export function GetVPCDetail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.VPCDetailResult>;

export function ListVSwitches(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.VSwitchListResult>;

export function ListSLBs(arg1:string,arg2:string,arg3:string):Promise<main.SLBListResult>;

export function GetSLBDetail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SLBDetailResult>;

export function ListSLBListeners(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SLBListenerListResult>;

export function ListConfigProfiles():Promise<Array<string>>;

export function GetCurrentProfile():Promise<string>;

export function SwitchProfile(arg1:string):Promise<void>;

export function GetProfileCredentials(arg1:string):Promise<main.ProfileCredentials>;

export function ExportSLSLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number):Promise<main.ExportResult>;
