// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetECSDetail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetECSDetail'](arg1, arg2, arg3, arg4);
}

export function GetECSMetrics(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetECSMetrics'](arg1, arg2, arg3, arg4);
}

export function GetECSMetricsMultiRegion(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetECSMetricsMultiRegion'](arg1, arg2, arg3);
}

export function ListOSSBuckets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListOSSBuckets'](arg1, arg2, arg3);
}

export function ListOSSObjects(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListOSSObjects'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListSLSLogStores(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSLSLogStores'](arg1, arg2, arg3, arg4);
}

export function MaskKey(arg1) {
  return window['go']['main']['App']['MaskKey'](arg1);
}

export function QueryECS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryECS'](arg1, arg2, arg3, arg4);
}

export function QueryECSMultiRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryECSMultiRegion'](arg1, arg2, arg3, arg4);
}

export function QuerySLSLogs(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['QuerySLSLogs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function QuerySLSLogsStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['QuerySLSLogsStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RebootECS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RebootECS'](arg1, arg2, arg3, arg4, arg5);
}

export function StartECS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartECS'](arg1, arg2, arg3, arg4);
}

export function StopECS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StopECS'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSupportedCloudProducts() {
  return window['go']['main']['App']['GetSupportedCloudProducts']();
}

export function GetCloudProductMetrics(arg1) {
  return window['go']['main']['App']['GetCloudProductMetrics'](arg1);
}

export function ListVPCs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListVPCs'](arg1, arg2, arg3);
}

export function GetVPCDetail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVPCDetail'](arg1, arg2, arg3, arg4);
}

export function ListVSwitches(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListVSwitches'](arg1, arg2, arg3, arg4);
}

export function ListSLBs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSLBs'](arg1, arg2, arg3);
}

export function GetSLBDetail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSLBDetail'](arg1, arg2, arg3, arg4);
}

export function ListSLBListeners(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSLBListeners'](arg1, arg2, arg3, arg4);
}
